version: 2

sphinx:
  builder: html
  configuration: documentation/doc/source/conf.py
  fail_on_warning: false

python:
   version: 3.9
   install:
      - requirements: documentation/doc/source/requirements.txt
      - method: pip
        path: .
   system_packages: true